# Generated by Django 4.2 on 2023-12-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_app', '0002_alter_department_parent_remove_unit_role_unit_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='department',
        ),
        migrations.AddField(
            model_name='role',
            name='department',
            field=models.ManyToManyField(blank=True, null=True, related_name='roles', to='organization_app.department', verbose_name='Подразделение'),
        ),
    ]
